# Generated by Django 4.2.10 on 2024-02-21 22:01

from django.db import migrations
from ..models import Building
import pgvector.django
import numpy as np


def generate_random_embedding(dim=640) -> np.ndarray:
    return np.random.rand(dim)

def add_embeddings_to_buildings(apps, schema_editor):
    for building in Building.objects.all():
        building.embedding = generate_random_embedding().tolist()
        building.save()

class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=640, null=True),
        ),
        migrations.RunPython(add_embeddings_to_buildings)
    ]
