# Generated by Django 4.2.10 on 2024-02-27 22:32

from django.db import migrations, models
from django.contrib.contenttypes.models import ContentType
from ..models import HousingCompany, PropertyManager, CustomTag

import random
import django.db.models.deletion


def make_data(apps, schema_editor):

    tags = []

    architecture_types = ["modern", "gothic", "classic", "neoclassical", "islamic"]
    for hc in HousingCompany.objects.all():
        tag = CustomTag(
            object_id=hc.id,
            content_type=ContentType.objects.get_for_model(HousingCompany),
            category="custom",
            name=random.choice(architecture_types),
            confidence=random.random() * 100
        )
        tags.append(tag)

    property_manager_types = ["hard-hitting", "noob", "amateur", "pro", "high-potential"]
    for pm in PropertyManager.objects.all():
        tag = CustomTag(
            object_id=pm.id,
            content_type=ContentType.objects.get_for_model(PropertyManager),
            category="custom",
            name=random.choice(property_manager_types),
            confidence=random.random() * 100
        )
        tags.append(tag)

    CustomTag.objects.bulk_create(tags)


def delete_data(apps, schema_editor):
    CustomTag.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('example', '0002_tag_taggeditem_housingcompany_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('category', models.CharField(db_index=True, default='custom', max_length=200)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('confidence', models.FloatField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.RunPython(make_data, delete_data)
    ]
