# Generated by Django 4.2.10 on 2024-02-29 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_library_segmentpropertags_taggeditemdefaultuuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentpropertags',
            name='video_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='example.videoasset'),
        ),
    ]
