# Generated by Django 4.2.11 on 2024-03-06 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_alter_segmentpropertags_video_asset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Apartment', 'verbose_name_plural': 'Apartments'},
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Building', 'verbose_name_plural': 'Buildings'},
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'verbose_name': 'Developer', 'verbose_name_plural': 'Developers'},
        ),
        migrations.AlterModelOptions(
            name='housingcompany',
            options={'verbose_name': 'Housing company', 'verbose_name_plural': 'Housing companies'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Owner', 'verbose_name_plural': 'Owners'},
        ),
        migrations.AlterModelOptions(
            name='postalcode',
            options={'verbose_name': 'Postal code', 'verbose_name_plural': 'Postal codes'},
        ),
        migrations.AlterModelOptions(
            name='propertymanager',
            options={'verbose_name': 'Property manager', 'verbose_name_plural': 'Property managers'},
        ),
        migrations.AlterModelOptions(
            name='realestate',
            options={'verbose_name': 'Real estate', 'verbose_name_plural': 'Real estates'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
    ]
