# Generated by Django 3.2.16 on 2024-03-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_alter_apartment_options_alter_building_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentpropertags',
            name='in_time',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segmentpropertags',
            name='in_time_base',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='segmentpropertags',
            name='out_time',
            field=models.IntegerField(default=10.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segmentpropertags',
            name='out_time_base',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='example',
            name='symmetrical_field',
            field=models.ManyToManyField(related_name='_example_example_symmetrical_field_+', to='example.Example'),
        ),
    ]
