# Generated by Django 4.2.11 on 2024-03-07 04:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0007_auto_20240306_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='symmetrical_field',
            field=models.ManyToManyField(to='example.example'),
        ),
        migrations.AlterField(
            model_name='housingcompany',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
