# Generated by Django 4.2.11 on 2024-03-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0008_alter_example_symmetrical_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('example.developer',),
        ),
        migrations.AlterField(
            model_name='housingcompany',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
