# Generated by Django 4.2.10 on 2024-03-08 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0009_developerproxy_alter_housingcompany_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingcompany',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='propertymanager',
            name='tags',
        ),
        migrations.AlterField(
            model_name='housingcompany',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
